Added Arabic Musnad Imam Abu Hanifa
fawazahmed0/hadith-api pull request #76
Opened 2024-02-18 04:00 UTC by GibreelAbdullah

Source - https://shamela.ws/book/29120

2024-02-18 13:20 UTC, fawazahmed0 requested changes

2024-02-18 13:20 UTC, fawazahmed0 commented on info.json
> +                "1":"كتاب الإيمان والإسلام والقدر والشفاعة",
Please use english section names

2024-02-18 13:58 UTC, GibreelAbdullah commented on info.json
> +                "1":"كتاب الإيمان والإسلام والقدر والشفاعة",
English translation is not available.

2024-02-18 21:43 UTC, fawazahmed0 commented
Jazakallah

2024-02-18 21:43 UTC, merged

2024-04-07 17:16 UTC, fawazahmed0 commented
Salam, I recently came to know that the book might have issues with authenticity. Please [see this](https://islam.stackexchange.com/a/83172/60349). It might be better to remove the book. Anyways Jazakallah for the hardwork.

2024-04-15 04:01 UTC, GibreelAbdullah commented
WaAlaikumAsSalam

This book is famous among the Hanafis as being attributed to Imam Abu Hanifa, even though it is compiled later by the students of his students.

There were various Masaneed of Imam Abu Hanifa and Imam Haskafi combined them into [one book](https://shamela.ws/book/29120)

There are many who have even written Sharh of this book including

- [Mulla Ali Qari d. 1014H](https://shamela.ws/book/9060)
- [Imam Muhammad 'Abid al-Sindi (d. 1257H)](https://archive.org/details/mwahib-latifa-shrah-musnad-abihanifa)

2024-04-15 06:16 UTC, fawazahmed0 commented
If this book had grades with it, then there would be no issue.
Also if you have noticed, Shuaib Al Arnaut who was a hanafi muhaddith, decided to authenticate musnad ahmad, but not this book.